import { LOCALES, type Locale } from "@/i18n/locale";
import { createTranslator, type MessageKey } from "@/i18n/translator";

/**
 * Payment texts generated by the offer form. Company/template defaults may contain one
 * of these strings in another language, especially defaults created before document i18n.
 * Exact matching lets us translate system text without touching company-authored wording.
 */
const STANDARD_PAYMENT_TERM_KEYS: readonly MessageKey[] = [
  "offer.doc.payment.cash",
  "offer.doc.payment.net10",
  "offer.doc.payment.deposit50",
  "offer.doc.payment.net30",
  "offer.doc.payment.invoice",
  "offer.doc.payment.twint",
  "offer.doc.payment.card",
  "offer.doc.paymentMethod.bar",
  "offer.doc.paymentMethod.rechnung_14",
  "offer.doc.paymentMethod.rechnung_30",
  "offer.doc.paymentMethod.twint",
  "offer.doc.paymentMethod.vorauskasse",
  "offer.doc.paymentMethod.teilzahlung",
] as const;

const normalize = (value: string): string =>
  value.trim().replace(/\s+/g, " ").toLocaleLowerCase();

const TERM_KEY_BY_TEXT = new Map<string, MessageKey>();

for (const sourceLocale of LOCALES) {
  const sourceT = createTranslator(sourceLocale);
  for (const key of STANDARD_PAYMENT_TERM_KEYS) {
    // Some quick-pick and payment-method keys intentionally resolve to the same sentence.
    // Keeping the first key is safe because their target translations have equal meaning.
    if (!TERM_KEY_BY_TEXT.has(normalize(sourceT(key)))) {
      TERM_KEY_BY_TEXT.set(normalize(sourceT(key)), key);
    }
  }
}

export const localizeStandardPaymentTerms = (
  value: string | null | undefined,
  targetLocale: Locale,
): string | null => {
  if (!value?.trim()) return null;
  const key = TERM_KEY_BY_TEXT.get(normalize(value));
  return key ? createTranslator(targetLocale)(key) : value;
};
