-- ERZEUGT von scripts/refresh-test-baseline.sh — nicht von Hand aendern.
-- Bildet die EXECUTE-Rechte der Produktion nach. Siehe Skriptkommentar.
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.activate_manual_import(p_company_id uuid, p_admin_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.activate_manual_import(p_company_id uuid, p_admin_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.activate_manual_import(p_company_id uuid, p_admin_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.activate_self_trial(p_days integer) TO anon;
GRANT EXECUTE ON FUNCTION public.activate_self_trial(p_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.activate_self_trial(p_days integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.agb_content_hash(p_access_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.agb_content_hash(p_access_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.agb_content_hash(p_access_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.appointments_set_customer() TO anon;
GRANT EXECUTE ON FUNCTION public.appointments_set_customer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.appointments_set_customer() TO service_role;
GRANT EXECUTE ON FUNCTION public.archive_and_purge_company_data(p_company_id uuid, p_retention_days integer) TO anon;
GRANT EXECUTE ON FUNCTION public.archive_and_purge_company_data(p_company_id uuid, p_retention_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.archive_and_purge_company_data(p_company_id uuid, p_retention_days integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.archive_returned_boxes() TO anon;
GRANT EXECUTE ON FUNCTION public.archive_returned_boxes() TO authenticated;
GRANT EXECUTE ON FUNCTION public.archive_returned_boxes() TO service_role;
GRANT EXECUTE ON FUNCTION public.atomic_adjust_token_balance(p_company_id uuid, p_amount numeric, p_type text, p_description text, p_payment_method text, p_payment_reference text, p_reference_type text, p_reference_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.atomic_adjust_token_balance(p_company_id uuid, p_amount numeric, p_type text, p_description text, p_payment_method text, p_payment_reference text, p_reference_type text, p_reference_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.atomic_adjust_token_balance(p_company_id uuid, p_amount numeric, p_type text, p_description text, p_payment_method text, p_payment_reference text, p_reference_type text, p_reference_id text) TO service_role;
GRANT EXECUTE ON FUNCTION public.atomic_confirm_lead(p_confirmation_id uuid, p_lead_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.atomic_confirm_lead(p_confirmation_id uuid, p_lead_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.atomic_confirm_lead(p_confirmation_id uuid, p_lead_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.auftraege_set_customer() TO anon;
GRANT EXECUTE ON FUNCTION public.auftraege_set_customer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.auftraege_set_customer() TO service_role;
GRANT EXECUTE ON FUNCTION public.beleg_set_customer() TO anon;
GRANT EXECUTE ON FUNCTION public.beleg_set_customer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.beleg_set_customer() TO service_role;
GRANT EXECUTE ON FUNCTION public.calculate_appointment_duration() TO anon;
GRANT EXECUTE ON FUNCTION public.calculate_appointment_duration() TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_appointment_duration() TO service_role;
GRANT EXECUTE ON FUNCTION public.calculate_distance_km(lat1 numeric, lon1 numeric, lat2 numeric, lon2 numeric) TO anon;
GRANT EXECUTE ON FUNCTION public.calculate_distance_km(lat1 numeric, lon1 numeric, lat2 numeric, lon2 numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_distance_km(lat1 numeric, lon1 numeric, lat2 numeric, lon2 numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.calculate_lead_spam_score() TO anon;
GRANT EXECUTE ON FUNCTION public.calculate_lead_spam_score() TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_lead_spam_score() TO service_role;
GRANT EXECUTE ON FUNCTION public.calculate_min_token_price(p_service_type text, p_max_companies integer) TO anon;
GRANT EXECUTE ON FUNCTION public.calculate_min_token_price(p_service_type text, p_max_companies integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_min_token_price(p_service_type text, p_max_companies integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.can_modify_role(modifier_id uuid, target_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.can_modify_role(modifier_id uuid, target_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_modify_role(modifier_id uuid, target_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.check_besichtigung_storage_access(folder_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.check_besichtigung_storage_access(folder_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_besichtigung_storage_access(folder_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_archived_boxes() TO anon;
GRANT EXECUTE ON FUNCTION public.cleanup_archived_boxes() TO authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_archived_boxes() TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_besichtigung_data() TO anon;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_besichtigung_data() TO authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_besichtigung_data() TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_inbound_emails(p_rejected_days integer, p_failed_days integer, p_converted_days integer) TO anon;
GRANT EXECUTE ON FUNCTION public.cleanup_inbound_emails(p_rejected_days integer, p_failed_days integer, p_converted_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_inbound_emails(p_rejected_days integer, p_failed_days integer, p_converted_days integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.companies_ensure_owner_membership() TO anon;
GRANT EXECUTE ON FUNCTION public.companies_ensure_owner_membership() TO authenticated;
GRANT EXECUTE ON FUNCTION public.companies_ensure_owner_membership() TO service_role;
GRANT EXECUTE ON FUNCTION public.consume_rate_limit(p_key text, p_window_ms integer, p_max_requests integer) TO anon;
GRANT EXECUTE ON FUNCTION public.consume_rate_limit(p_key text, p_window_ms integer, p_max_requests integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.consume_rate_limit(p_key text, p_window_ms integer, p_max_requests integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_appointment_from_lead(p_lead_id uuid, p_company_id uuid, p_appointment_type character varying, p_appointment_date date, p_start_time time without time zone, p_end_time time without time zone, p_title character varying) TO anon;
GRANT EXECUTE ON FUNCTION public.create_appointment_from_lead(p_lead_id uuid, p_company_id uuid, p_appointment_type character varying, p_appointment_date date, p_start_time time without time zone, p_end_time time without time zone, p_title character varying) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_appointment_from_lead(p_lead_id uuid, p_company_id uuid, p_appointment_type character varying, p_appointment_date date, p_start_time time without time zone, p_end_time time without time zone, p_title character varying) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_appointments_for_auftrag() TO anon;
GRANT EXECUTE ON FUNCTION public.create_appointments_for_auftrag() TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_appointments_for_auftrag() TO service_role;
GRANT EXECUTE ON FUNCTION public.create_archive_log(p_archive_name text, p_archive_type text, p_records_count integer, p_storage_type text, p_storage_path text, p_export_format text, p_triggered_by text, p_user_id uuid, p_data_from timestamp with time zone, p_data_to timestamp with time zone) TO anon;
GRANT EXECUTE ON FUNCTION public.create_archive_log(p_archive_name text, p_archive_type text, p_records_count integer, p_storage_type text, p_storage_path text, p_export_format text, p_triggered_by text, p_user_id uuid, p_data_from timestamp with time zone, p_data_to timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_archive_log(p_archive_name text, p_archive_type text, p_records_count integer, p_storage_type text, p_storage_path text, p_export_format text, p_triggered_by text, p_user_id uuid, p_data_from timestamp with time zone, p_data_to timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_besichtigung_session(p_company_id uuid, p_customer_name text, p_customer_email text, p_customer_phone text, p_lead_id uuid, p_offer_id uuid, p_from_address text, p_from_plz text, p_from_city text, p_expires_days integer, p_created_by uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.create_besichtigung_session(p_company_id uuid, p_customer_name text, p_customer_email text, p_customer_phone text, p_lead_id uuid, p_offer_id uuid, p_from_address text, p_from_plz text, p_from_city text, p_expires_days integer, p_created_by uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_besichtigung_session(p_company_id uuid, p_customer_name text, p_customer_email text, p_customer_phone text, p_lead_id uuid, p_offer_id uuid, p_from_address text, p_from_plz text, p_from_city text, p_expires_days integer, p_created_by uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_company_after_signup(p_user_id uuid, p_company_name text, p_legal_name text, p_street text, p_house_number text, p_plz text, p_city text, p_phone text, p_email text, p_website text, p_services text[], p_coverage_plz text, p_coverage_radius integer) TO anon;
GRANT EXECUTE ON FUNCTION public.create_company_after_signup(p_user_id uuid, p_company_name text, p_legal_name text, p_street text, p_house_number text, p_plz text, p_city text, p_phone text, p_email text, p_website text, p_services text[], p_coverage_plz text, p_coverage_radius integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_company_after_signup(p_user_id uuid, p_company_name text, p_legal_name text, p_street text, p_house_number text, p_plz text, p_city text, p_phone text, p_email text, p_website text, p_services text[], p_coverage_plz text, p_coverage_radius integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_lead_from_inbound_email(p_inbound_id uuid, p_company_id uuid, p_lead jsonb, p_outcome jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_offer_amendment(p_offer_id uuid, p_title text, p_reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_offer_amendment(p_offer_id uuid, p_title text, p_reason text) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_offer_revision(p_offer_id uuid, p_reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_offer_revision(p_offer_id uuid, p_reason text) TO service_role;
GRANT EXECUTE ON FUNCTION public.customer_backfill_quellen(p_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.customer_backfill_quellen(p_company_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.customer_merge_preview(p_company_id uuid, p_source_customer_id uuid, p_target_customer_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.customer_merge_preview(p_company_id uuid, p_source_customer_id uuid, p_target_customer_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.customer_summary(p_customer_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.customer_summary(p_customer_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.customer_timeline(p_customer_id uuid, p_limit integer, p_offset integer, p_before timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.customer_timeline(p_customer_id uuid, p_limit integer, p_offset integer, p_before timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.customers_set_display_name() TO anon;
GRANT EXECUTE ON FUNCTION public.customers_set_display_name() TO authenticated;
GRANT EXECUTE ON FUNCTION public.customers_set_display_name() TO service_role;
GRANT EXECUTE ON FUNCTION public.deactivate_expired_subscriptions() TO anon;
GRANT EXECUTE ON FUNCTION public.deactivate_expired_subscriptions() TO authenticated;
GRANT EXECUTE ON FUNCTION public.deactivate_expired_subscriptions() TO service_role;
GRANT EXECUTE ON FUNCTION public.deactivate_manual_import(p_company_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.deactivate_manual_import(p_company_id uuid, p_reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.deactivate_manual_import(p_company_id uuid, p_reason text) TO service_role;
GRANT EXECUTE ON FUNCTION public.debug_storage_objects() TO anon;
GRANT EXECUTE ON FUNCTION public.debug_storage_objects() TO authenticated;
GRANT EXECUTE ON FUNCTION public.debug_storage_objects() TO service_role;
GRANT EXECUTE ON FUNCTION public.delete_besichtigung_photo(p_photo_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.delete_besichtigung_photo(p_photo_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_besichtigung_photo(p_photo_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.duplicate_candidates(p_company_id uuid, p_customer_id uuid, p_limit integer, p_offset integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.duplicate_candidates(p_company_id uuid, p_customer_id uuid, p_limit integer, p_offset integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.execute_sql(query text, read_only boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.expire_unconfirmed_risky_leads() TO anon;
GRANT EXECUTE ON FUNCTION public.expire_unconfirmed_risky_leads() TO authenticated;
GRANT EXECUTE ON FUNCTION public.expire_unconfirmed_risky_leads() TO service_role;
GRANT EXECUTE ON FUNCTION public.expire_unverified_leads(p_hours_threshold integer, p_spam_score_max integer) TO anon;
GRANT EXECUTE ON FUNCTION public.expire_unverified_leads(p_hours_threshold integer, p_spam_score_max integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.expire_unverified_leads(p_hours_threshold integer, p_spam_score_max integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.extend_subscription(p_company_id uuid, p_months integer, p_confirmed_by uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.extend_subscription(p_company_id uuid, p_months integer, p_confirmed_by uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.extend_subscription(p_company_id uuid, p_months integer, p_confirmed_by uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.find_companies_fallback(target_plz character varying, service_type_filter character varying, fallback_radius_km numeric, max_results integer) TO anon;
GRANT EXECUTE ON FUNCTION public.find_companies_fallback(target_plz character varying, service_type_filter character varying, fallback_radius_km numeric, max_results integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.find_companies_fallback(target_plz character varying, service_type_filter character varying, fallback_radius_km numeric, max_results integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.find_companies_in_radius(target_plz character varying, service_type_filter character varying, max_results integer) TO anon;
GRANT EXECUTE ON FUNCTION public.find_companies_in_radius(target_plz character varying, service_type_filter character varying, max_results integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.find_companies_in_radius(target_plz character varying, service_type_filter character varying, max_results integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.find_customer_by_identity(p_company_id uuid, p_email text, p_phone text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.find_customer_by_identity(p_company_id uuid, p_email text, p_phone text) TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_auftrag_nummer() TO anon;
GRANT EXECUTE ON FUNCTION public.generate_auftrag_nummer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_auftrag_nummer() TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_klavier_nummer() TO anon;
GRANT EXECUTE ON FUNCTION public.generate_klavier_nummer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_klavier_nummer() TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_moebellift_nummer() TO anon;
GRANT EXECUTE ON FUNCTION public.generate_moebellift_nummer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_moebellift_nummer() TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_offer_number() TO anon;
GRANT EXECUTE ON FUNCTION public.generate_offer_number() TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_offer_number() TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_quittung_nr() TO anon;
GRANT EXECUTE ON FUNCTION public.generate_quittung_nr() TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_quittung_nr() TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_raeumung_nummer() TO anon;
GRANT EXECUTE ON FUNCTION public.generate_raeumung_nummer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_raeumung_nummer() TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_rechnung_nr() TO anon;
GRANT EXECUTE ON FUNCTION public.generate_rechnung_nr() TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_rechnung_nr() TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_recurring_appointments(p_parent_id uuid, p_end_date date) TO anon;
GRANT EXECUTE ON FUNCTION public.generate_recurring_appointments(p_parent_id uuid, p_end_date date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_recurring_appointments(p_parent_id uuid, p_end_date date) TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_umzug_nummer() TO anon;
GRANT EXECUTE ON FUNCTION public.generate_umzug_nummer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_umzug_nummer() TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_unique_slug(prefix text) TO anon;
GRANT EXECUTE ON FUNCTION public.generate_unique_slug(prefix text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_unique_slug(prefix text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_admin_activity_log(p_limit integer, p_offset integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_admin_activity_log(p_limit integer, p_offset integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_activity_log(p_limit integer, p_offset integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_agb_sections_by_offer_token(p_access_token text, p_service_type text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_agb_sections_by_offer_token(p_access_token text, p_service_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_agb_sections_by_offer_token(p_access_token text, p_service_type text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_amendment_by_token(p_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_amendment_by_token(p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_amendment_by_token(p_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_archivable_leads(retention_days integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_archivable_leads(retention_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_archivable_leads(retention_days integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_archivable_offers(retention_days integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_archivable_offers(retention_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_archivable_offers(retention_days integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_archive_statistics() TO anon;
GRANT EXECUTE ON FUNCTION public.get_archive_statistics() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_archive_statistics() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_auftraege_needing_customer_reminders() TO anon;
GRANT EXECUTE ON FUNCTION public.get_auftraege_needing_customer_reminders() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_auftraege_needing_customer_reminders() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_auftraege_needing_reminders() TO anon;
GRANT EXECUTE ON FUNCTION public.get_auftraege_needing_reminders() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_auftraege_needing_reminders() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_auth_audit_log(p_limit integer, p_offset integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_auth_audit_log(p_limit integer, p_offset integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_auth_audit_log(p_limit integer, p_offset integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_besichtigung_analysis(p_session_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_besichtigung_analysis(p_session_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_besichtigung_analysis(p_session_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_besichtigung_photos(p_session_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_besichtigung_photos(p_session_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_besichtigung_photos(p_session_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_besichtigung_session_by_token(p_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_besichtigung_session_by_token(p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_besichtigung_session_by_token(p_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_besichtigung_videos(p_session_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_besichtigung_videos(p_session_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_besichtigung_videos(p_session_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_box_rental_stats(p_company_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_box_rental_stats(p_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_box_rental_stats(p_company_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_checklist_by_offer_token(p_access_token text, p_service_type text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_checklist_by_offer_token(p_access_token text, p_service_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_checklist_by_offer_token(p_access_token text, p_service_type text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_companies_needing_reminders() TO anon;
GRANT EXECUTE ON FUNCTION public.get_companies_needing_reminders() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_companies_needing_reminders() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_company_besichtigung_sessions(p_company_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_company_besichtigung_sessions(p_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_company_besichtigung_sessions(p_company_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_company_id_from_offer_token(offer_id uuid, token text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_company_id_from_offer_token(offer_id uuid, token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_company_id_from_offer_token(offer_id uuid, token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_company_pricing_config(p_company_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_company_pricing_config(p_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_company_pricing_config(p_company_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_company_pricing_history(p_company_id uuid, p_limit integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_company_pricing_history(p_company_id uuid, p_limit integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_company_pricing_history(p_company_id uuid, p_limit integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_offer_by_token(offer_access_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_offer_by_token(offer_access_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_offer_by_token(offer_access_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_offer_items_by_token(p_access_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_offer_items_by_token(p_access_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_offer_items_by_token(p_access_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_plz_distance_km(plz1 character varying, plz2 character varying) TO anon;
GRANT EXECUTE ON FUNCTION public.get_plz_distance_km(plz1 character varying, plz2 character varying) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_plz_distance_km(plz1 character varying, plz2 character varying) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_public_company_info(company_uuid uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_public_company_info(company_uuid uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_company_info(company_uuid uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_role_level(role_name text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_role_level(role_name text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_role_level(role_name text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_total_box_quantity(box_items_json jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.get_total_box_quantity(box_items_json jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_total_box_quantity(box_items_json jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_user_company_ids() TO anon;
GRANT EXECUTE ON FUNCTION public.get_user_company_ids() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_company_ids() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_user_overview() TO anon;
GRANT EXECUTE ON FUNCTION public.get_user_overview() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_overview() TO service_role;
GRANT EXECUTE ON FUNCTION public.grant_trial(p_company_id uuid, p_days integer, p_granted_by uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.grant_trial(p_company_id uuid, p_days integer, p_granted_by uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.grant_trial(p_company_id uuid, p_days integer, p_granted_by uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.guard_amendment_after_send() TO anon;
GRANT EXECUTE ON FUNCTION public.guard_amendment_after_send() TO authenticated;
GRANT EXECUTE ON FUNCTION public.guard_amendment_after_send() TO service_role;
GRANT EXECUTE ON FUNCTION public.guard_company_ownership() TO anon;
GRANT EXECUTE ON FUNCTION public.guard_company_ownership() TO authenticated;
GRANT EXECUTE ON FUNCTION public.guard_company_ownership() TO service_role;
GRANT EXECUTE ON FUNCTION public.guard_customer_merge_fields() TO anon;
GRANT EXECUTE ON FUNCTION public.guard_customer_merge_fields() TO authenticated;
GRANT EXECUTE ON FUNCTION public.guard_customer_merge_fields() TO service_role;
GRANT EXECUTE ON FUNCTION public.guard_customer_merges_append_only() TO anon;
GRANT EXECUTE ON FUNCTION public.guard_customer_merges_append_only() TO authenticated;
GRANT EXECUTE ON FUNCTION public.guard_customer_merges_append_only() TO service_role;
GRANT EXECUTE ON FUNCTION public.guard_offer_content_after_send() TO anon;
GRANT EXECUTE ON FUNCTION public.guard_offer_content_after_send() TO authenticated;
GRANT EXECUTE ON FUNCTION public.guard_offer_content_after_send() TO service_role;
GRANT EXECUTE ON FUNCTION public.guard_quittung_delete() TO anon;
GRANT EXECUTE ON FUNCTION public.guard_quittung_delete() TO authenticated;
GRANT EXECUTE ON FUNCTION public.guard_quittung_delete() TO service_role;
GRANT EXECUTE ON FUNCTION public.guard_quittung_status_regression() TO anon;
GRANT EXECUTE ON FUNCTION public.guard_quittung_status_regression() TO authenticated;
GRANT EXECUTE ON FUNCTION public.guard_quittung_status_regression() TO service_role;
GRANT EXECUTE ON FUNCTION public.guard_rechnung_delete() TO anon;
GRANT EXECUTE ON FUNCTION public.guard_rechnung_delete() TO authenticated;
GRANT EXECUTE ON FUNCTION public.guard_rechnung_delete() TO service_role;
GRANT EXECUTE ON FUNCTION public.guard_rechnung_status_regression() TO anon;
GRANT EXECUTE ON FUNCTION public.guard_rechnung_status_regression() TO authenticated;
GRANT EXECUTE ON FUNCTION public.guard_rechnung_status_regression() TO service_role;
GRANT EXECUTE ON FUNCTION public.guard_stage_history_append_only() TO anon;
GRANT EXECUTE ON FUNCTION public.guard_stage_history_append_only() TO authenticated;
GRANT EXECUTE ON FUNCTION public.guard_stage_history_append_only() TO service_role;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO anon;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO authenticated;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO service_role;
GRANT EXECUTE ON FUNCTION public.handle_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.handle_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.handle_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role app_role) TO anon;
GRANT EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role app_role) TO service_role;
GRANT EXECUTE ON FUNCTION public.i18n_jsonb(p_base jsonb, p_translations jsonb, p_locale text, p_field text) TO anon;
GRANT EXECUTE ON FUNCTION public.i18n_jsonb(p_base jsonb, p_translations jsonb, p_locale text, p_field text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.i18n_jsonb(p_base jsonb, p_translations jsonb, p_locale text, p_field text) TO service_role;
GRANT EXECUTE ON FUNCTION public.i18n_text(p_base text, p_translations jsonb, p_locale text, p_field text) TO anon;
GRANT EXECUTE ON FUNCTION public.i18n_text(p_base text, p_translations jsonb, p_locale text, p_field text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.i18n_text(p_base text, p_translations jsonb, p_locale text, p_field text) TO service_role;
GRANT EXECUTE ON FUNCTION public.inbound_emails_set_customer() TO anon;
GRANT EXECUTE ON FUNCTION public.inbound_emails_set_customer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.inbound_emails_set_customer() TO service_role;
GRANT EXECUTE ON FUNCTION public.increment_blog_view_count(post_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.increment_blog_view_count(post_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.increment_blog_view_count(post_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.increment_manual_import_count(p_company_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.increment_manual_import_count(p_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.increment_manual_import_count(p_company_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.insert_besichtigung_photo(p_session_id uuid, p_storage_path text, p_filename text, p_file_size bigint, p_mime_type text, p_room_type text) TO anon;
GRANT EXECUTE ON FUNCTION public.insert_besichtigung_photo(p_session_id uuid, p_storage_path text, p_filename text, p_file_size bigint, p_mime_type text, p_room_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.insert_besichtigung_photo(p_session_id uuid, p_storage_path text, p_filename text, p_file_size bigint, p_mime_type text, p_room_type text) TO service_role;
GRANT EXECUTE ON FUNCTION public.invoke_appointment_reminder() TO anon;
GRANT EXECUTE ON FUNCTION public.invoke_appointment_reminder() TO authenticated;
GRANT EXECUTE ON FUNCTION public.invoke_appointment_reminder() TO service_role;
GRANT EXECUTE ON FUNCTION public.invoke_edge_function(p_fn text) TO anon;
GRANT EXECUTE ON FUNCTION public.invoke_edge_function(p_fn text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.invoke_edge_function(p_fn text) TO service_role;
GRANT EXECUTE ON FUNCTION public.invoke_team_reminder() TO anon;
GRANT EXECUTE ON FUNCTION public.invoke_team_reminder() TO authenticated;
GRANT EXECUTE ON FUNCTION public.invoke_team_reminder() TO service_role;
GRANT EXECUTE ON FUNCTION public.is_admin(_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_admin(_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin(_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_company_member(_company_id uuid, _user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_company_member(_company_id uuid, _user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_company_member(_company_id uuid, _user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_company_owner(_company_id uuid, _user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_company_owner(_company_id uuid, _user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_company_owner(_company_id uuid, _user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_company_role(_company_id uuid, _roles text[], _user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_company_role(_company_id uuid, _roles text[], _user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_company_role(_company_id uuid, _roles text[], _user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_company_visible_via_offer(company_uuid uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_company_visible_via_offer(company_uuid uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_company_visible_via_offer(company_uuid uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_crm_enabled(p_company_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_crm_enabled(p_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_crm_enabled(p_company_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_staff(_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_staff(_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_staff(_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_super_admin(_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.is_super_admin(_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_super_admin(_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_support_admin() TO anon;
GRANT EXECUTE ON FUNCTION public.is_support_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_support_admin() TO service_role;
GRANT EXECUTE ON FUNCTION public.leads_record_stage_change() TO anon;
GRANT EXECUTE ON FUNCTION public.leads_record_stage_change() TO authenticated;
GRANT EXECUTE ON FUNCTION public.leads_record_stage_change() TO service_role;
GRANT EXECUTE ON FUNCTION public.leads_set_customer() TO anon;
GRANT EXECUTE ON FUNCTION public.leads_set_customer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.leads_set_customer() TO service_role;
GRANT EXECUTE ON FUNCTION public.log_appointment_changes() TO anon;
GRANT EXECUTE ON FUNCTION public.log_appointment_changes() TO authenticated;
GRANT EXECUTE ON FUNCTION public.log_appointment_changes() TO service_role;
GRANT EXECUTE ON FUNCTION public.map_auftrag_to_appointment_status(p_status text) TO anon;
GRANT EXECUTE ON FUNCTION public.map_auftrag_to_appointment_status(p_status text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.map_auftrag_to_appointment_status(p_status text) TO service_role;
GRANT EXECUTE ON FUNCTION public.merge_customers(p_company_id uuid, p_source_customer_id uuid, p_target_customer_id uuid, p_reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.merge_customers(p_company_id uuid, p_source_customer_id uuid, p_target_customer_id uuid, p_reason text) TO service_role;
GRANT EXECUTE ON FUNCTION public.normalize_customer_email(p_email text) TO anon;
GRANT EXECUTE ON FUNCTION public.normalize_customer_email(p_email text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.normalize_customer_email(p_email text) TO service_role;
GRANT EXECUTE ON FUNCTION public.normalize_customer_phone(p_phone text) TO anon;
GRANT EXECUTE ON FUNCTION public.normalize_customer_phone(p_phone text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.normalize_customer_phone(p_phone text) TO service_role;
GRANT EXECUTE ON FUNCTION public.notify_offer_response() TO anon;
GRANT EXECUTE ON FUNCTION public.notify_offer_response() TO authenticated;
GRANT EXECUTE ON FUNCTION public.notify_offer_response() TO service_role;
GRANT EXECUTE ON FUNCTION public.offer_amendments_inherit() TO anon;
GRANT EXECUTE ON FUNCTION public.offer_amendments_inherit() TO authenticated;
GRANT EXECUTE ON FUNCTION public.offer_amendments_inherit() TO service_role;
GRANT EXECUTE ON FUNCTION public.offers_advance_lead_stage() TO anon;
GRANT EXECUTE ON FUNCTION public.offers_advance_lead_stage() TO authenticated;
GRANT EXECUTE ON FUNCTION public.offers_advance_lead_stage() TO service_role;
GRANT EXECUTE ON FUNCTION public.offers_set_customer() TO anon;
GRANT EXECUTE ON FUNCTION public.offers_set_customer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.offers_set_customer() TO service_role;
GRANT EXECUTE ON FUNCTION public.offers_set_series() TO anon;
GRANT EXECUTE ON FUNCTION public.offers_set_series() TO authenticated;
GRANT EXECUTE ON FUNCTION public.offers_set_series() TO service_role;
GRANT EXECUTE ON FUNCTION public.preview_customer_backfill(p_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.preview_customer_backfill(p_company_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.reap_stuck_inbound_emails(p_minutes integer) TO anon;
GRANT EXECUTE ON FUNCTION public.reap_stuck_inbound_emails(p_minutes integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reap_stuck_inbound_emails(p_minutes integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.reap_stuck_sending_offers() TO anon;
GRANT EXECUTE ON FUNCTION public.reap_stuck_sending_offers() TO authenticated;
GRANT EXECUTE ON FUNCTION public.reap_stuck_sending_offers() TO service_role;
GRANT EXECUTE ON FUNCTION public.replace_offer_items(p_offer_id uuid, p_items jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.replace_offer_items(p_offer_id uuid, p_items jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.replace_offer_items(p_offer_id uuid, p_items jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.resolve_or_create_customer(p_company_id uuid, p_email text, p_phone text, p_first_name text, p_last_name text, p_company_name text, p_salutation text, p_language text, p_source text, p_seen_at timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.resolve_or_create_customer(p_company_id uuid, p_email text, p_phone text, p_first_name text, p_last_name text, p_company_name text, p_salutation text, p_language text, p_source text, p_seen_at timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.run_customer_backfill(p_company_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.run_customer_backfill(p_company_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.run_pipeline_automations() TO service_role;
GRANT EXECUTE ON FUNCTION public.save_besichtigung_analysis(p_session_id uuid, p_estimated_volume_m3 numeric, p_estimated_time_hours numeric, p_recommended_workers integer, p_recommended_truck text, p_room_breakdown jsonb, p_detected_items jsonb, p_special_items text[], p_special_requirements text[], p_from_access_difficulty text, p_from_floor integer, p_from_has_lift boolean, p_from_parking_distance text, p_confidence numeric, p_raw_response jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.save_besichtigung_analysis(p_session_id uuid, p_estimated_volume_m3 numeric, p_estimated_time_hours numeric, p_recommended_workers integer, p_recommended_truck text, p_room_breakdown jsonb, p_detected_items jsonb, p_special_items text[], p_special_requirements text[], p_from_access_difficulty text, p_from_floor integer, p_from_has_lift boolean, p_from_parking_distance text, p_confidence numeric, p_raw_response jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_besichtigung_analysis(p_session_id uuid, p_estimated_volume_m3 numeric, p_estimated_time_hours numeric, p_recommended_workers integer, p_recommended_truck text, p_room_breakdown jsonb, p_detected_items jsonb, p_special_items text[], p_special_requirements text[], p_from_access_difficulty text, p_from_floor integer, p_from_has_lift boolean, p_from_parking_distance text, p_confidence numeric, p_raw_response jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.save_moving_calculation(p_offer_id uuid, p_calculation_data jsonb, p_origin_building_info jsonb, p_destination_building_info jsonb, p_distance_km numeric, p_driving_time_minutes integer, p_additional_stops integer, p_inventory_items jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.save_moving_calculation(p_offer_id uuid, p_calculation_data jsonb, p_origin_building_info jsonb, p_destination_building_info jsonb, p_distance_km numeric, p_driving_time_minutes integer, p_additional_stops integer, p_inventory_items jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_moving_calculation(p_offer_id uuid, p_calculation_data jsonb, p_origin_building_info jsonb, p_destination_building_info jsonb, p_distance_km numeric, p_driving_time_minutes integer, p_additional_stops integer, p_inventory_items jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.schedule_besichtigung_cleanup(p_company_id uuid, p_lead_id uuid, p_days integer) TO anon;
GRANT EXECUTE ON FUNCTION public.schedule_besichtigung_cleanup(p_company_id uuid, p_lead_id uuid, p_days integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.schedule_besichtigung_cleanup(p_company_id uuid, p_lead_id uuid, p_days integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.search_customers(p_company_id uuid, p_query text, p_filter text, p_limit integer, p_offset integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.search_customers(p_company_id uuid, p_query text, p_filter text, p_limit integer, p_offset integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_api_keys_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.set_api_keys_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_api_keys_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.set_company_slug() TO anon;
GRANT EXECUTE ON FUNCTION public.set_company_slug() TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_company_slug() TO service_role;
GRANT EXECUTE ON FUNCTION public.set_lead_slug() TO anon;
GRANT EXECUTE ON FUNCTION public.set_lead_slug() TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_lead_slug() TO service_role;
GRANT EXECUTE ON FUNCTION public.set_offer_acceptance_evidence() TO anon;
GRANT EXECUTE ON FUNCTION public.set_offer_acceptance_evidence() TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_offer_acceptance_evidence() TO service_role;
GRANT EXECUTE ON FUNCTION public.submit_lead(p_service_type text, p_from_plz text, p_from_city text, p_from_street text, p_from_house_number text, p_customer_first_name text, p_customer_last_name text, p_customer_email text, p_customer_phone text, p_preferred_date date, p_description text, p_property_type text, p_from_rooms numeric, p_from_living_space_m2 integer, p_detailed_form_data jsonb, p_form_version integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_lead(p_service_type text, p_from_plz text, p_from_city text, p_from_street text, p_from_house_number text, p_customer_first_name text, p_customer_last_name text, p_customer_email text, p_customer_phone text, p_preferred_date date, p_description text, p_property_type text, p_from_rooms numeric, p_from_living_space_m2 integer, p_detailed_form_data jsonb, p_form_version integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.submit_lead_json(lead_data jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_lead_json(lead_data jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_appointment_cancel_to_auftrag() TO anon;
GRANT EXECUTE ON FUNCTION public.sync_appointment_cancel_to_auftrag() TO authenticated;
GRANT EXECUTE ON FUNCTION public.sync_appointment_cancel_to_auftrag() TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_appointment_schedule_to_auftrag() TO anon;
GRANT EXECUTE ON FUNCTION public.sync_appointment_schedule_to_auftrag() TO authenticated;
GRANT EXECUTE ON FUNCTION public.sync_appointment_schedule_to_auftrag() TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_auftrag_status_to_appointment() TO anon;
GRANT EXECUTE ON FUNCTION public.sync_auftrag_status_to_appointment() TO authenticated;
GRANT EXECUTE ON FUNCTION public.sync_auftrag_status_to_appointment() TO service_role;
GRANT EXECUTE ON FUNCTION public.trigger_notify_admin_high_spam() TO anon;
GRANT EXECUTE ON FUNCTION public.trigger_notify_admin_high_spam() TO authenticated;
GRANT EXECUTE ON FUNCTION public.trigger_notify_admin_high_spam() TO service_role;
GRANT EXECUTE ON FUNCTION public.trigger_subscription_manager() TO anon;
GRANT EXECUTE ON FUNCTION public.trigger_subscription_manager() TO authenticated;
GRANT EXECUTE ON FUNCTION public.trigger_subscription_manager() TO service_role;
GRANT EXECUTE ON FUNCTION public.trigger_team_reminder_for_appointment(p_appointment_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.trigger_team_reminder_for_appointment(p_appointment_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.trigger_team_reminder_for_appointment(p_appointment_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.update_amendment_by_token(p_token text, p_new_status text, p_note text, p_ip text) TO anon;
GRANT EXECUTE ON FUNCTION public.update_amendment_by_token(p_token text, p_new_status text, p_note text, p_ip text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_amendment_by_token(p_token text, p_new_status text, p_note text, p_ip text) TO service_role;
GRANT EXECUTE ON FUNCTION public.update_archive_timestamp() TO anon;
GRANT EXECUTE ON FUNCTION public.update_archive_timestamp() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_archive_timestamp() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_besichtigung_session_status(p_session_id uuid, p_status text, p_customer_notes text) TO anon;
GRANT EXECUTE ON FUNCTION public.update_besichtigung_session_status(p_session_id uuid, p_status text, p_customer_notes text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_besichtigung_session_status(p_session_id uuid, p_status text, p_customer_notes text) TO service_role;
GRANT EXECUTE ON FUNCTION public.update_company_pricing_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_company_pricing_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_company_pricing_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_klaviertransport_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_klaviertransport_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_klaviertransport_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_landing_pages_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_landing_pages_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_landing_pages_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_manual_import_sub_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_manual_import_sub_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_manual_import_sub_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_moebellift_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_moebellift_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_moebellift_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_offer_by_token(offer_access_token text, new_status text, new_viewed_at timestamp with time zone, new_accepted_at timestamp with time zone, new_rejected_at timestamp with time zone, new_customer_response_note text, new_agb_accepted_at timestamp with time zone, new_agb_version text, new_agb_ip_address text) TO anon;
GRANT EXECUTE ON FUNCTION public.update_offer_by_token(offer_access_token text, new_status text, new_viewed_at timestamp with time zone, new_accepted_at timestamp with time zone, new_rejected_at timestamp with time zone, new_customer_response_note text, new_agb_accepted_at timestamp with time zone, new_agb_version text, new_agb_ip_address text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_offer_by_token(offer_access_token text, new_status text, new_viewed_at timestamp with time zone, new_accepted_at timestamp with time zone, new_rejected_at timestamp with time zone, new_customer_response_note text, new_agb_accepted_at timestamp with time zone, new_agb_version text, new_agb_ip_address text) TO service_role;
GRANT EXECUTE ON FUNCTION public.update_quittungen_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_quittungen_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_quittungen_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_raeumung_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_raeumung_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_raeumung_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_rechnungen_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_rechnungen_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_rechnungen_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_ticket_timestamp() TO anon;
GRANT EXECUTE ON FUNCTION public.update_ticket_timestamp() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_ticket_timestamp() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_umzug_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_umzug_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_umzug_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_umzugsbox_rentals_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_umzugsbox_rentals_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_umzugsbox_rentals_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_website_settings_timestamp() TO anon;
GRANT EXECUTE ON FUNCTION public.update_website_settings_timestamp() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_website_settings_timestamp() TO service_role;
GRANT EXECUTE ON FUNCTION public.upsert_company_pricing_config(p_company_id uuid, p_config jsonb, p_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.upsert_company_pricing_config(p_company_id uuid, p_config jsonb, p_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.upsert_company_pricing_config(p_company_id uuid, p_config jsonb, p_user_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.validate_offer_access_token(offer_id uuid, token text) TO anon;
GRANT EXECUTE ON FUNCTION public.validate_offer_access_token(offer_id uuid, token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.validate_offer_access_token(offer_id uuid, token text) TO service_role;
